version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/userDB
    volumes:
      - ./web_server:/home/web_server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo_db:/docker-entrypoint-initdb.d
